### ISSUE TITLE
Art Walk August 25

### ISSUE THREAD

**Issue by MelissaIuliano** [saw-comics-gnv/planning#8]
GOAL: SAW has an awesome offering for ArtWalk that gets people super jazzed about SAW-- both new students (who know they can have a show) and community members. 

This will be at SAW

- [x] @zee-em to email james re: screen printing and his own work, cc melissa
- [x] advertise via Facebook
- [x] apply for Art Walk http://www.artwalkgainesville.com/services - DUE DATE the 15th (of whatever month you want to be in the art walk
- [x] request DJ-- ask Don
- [x] get people to hang out
- [x] create signage --
- [x] get lights and fringe

**Comment by zee-em** [comment]
hi @MelissaIuliano as I mentioned, James confirmed that he's up for this. I will coax some images from him next week. 
@no-carrier, are you willing to DJ? I think it will be at Old SAW.
@hutchowen -- is this true? do we prefer Old SAW for artwalk?

**Comment by hutchowen** [comment]
Until we can assess situation at NEW SAW, yes. They will probably be building back there through October.

**Comment by MelissaIuliano** [comment]
Hey guys! I'm emailing the Artwalk people and checking in here just to make sure I get all the info right before submitting our showcase to them. 

Since we are doing a combo showcase of both James Turek's work and the student work from the silk screen workshop, _should we have an exhibit name_? (ooh la la!!) Like, "James Turek and the Silk Screeners" or something? That makes it sound like a band name...which is cute. or "Screens of Silk" or...something. I don't know, just spit-balling right now.
What are y'all thoughts on exhibit names? Should we bother doing an exhibit name or just call it "James Turek/ August Silk Screen Showcase"? 

@hutchowen - so yes, it's going to be at Old SAW, right? What is the exact address of Old SAW? I have it down as 18 SE 5th Ave on my google map app. Is that right?? 
Also: here is the link to the payment option https://www.artwalkgainesville.com/venue-payment
I haven't sent the email just yet (waiting to makes sure I have all the right info to send to the Artwalk people). Don't pay until I send the email.

@zee-em already emailed James so we'll be getting images and an artist statement soon :) 

woop woop! It's gonna be a great show!

**Comment by hutchowen** [comment]
Yes to all!

I"ll pay the fee, you can tell them that in the email too, they're used to me.

Cheers and THANKS!!!!!

**Comment by mmmaxine** [comment]
Thanks for taking care of this @MelissaIuliano ! <3 I like both title ideas.

**Comment by MelissaIuliano** [comment]
@hutchowen - I am not able to make a FB Eventpage on the main SAW FB. I can only make one on the other SAW groups (but even then, it shows ME as hosting it and it limits me from inviting everyone for some reason?) Tom - would you be able to either create the FB Event for this artwalk or let me have access as a moderator to the main SAW FB page? I realize this is very last minute. I just couldn't figure out out to do it on the main FB page. I can email you the info so all you have to do is cut and paste, if that makes it easier.

@zee-em & @no-carrier - Are we good for music? It would be awesome if you could DJ :) 

* * * * ALSO and most importantly: I have work during this Artwalk (Friday concert series. sigh) So I will not be able to be the main hostess/ in the building for this one. I can definitely set up and take down art (Before 4pm and after 11pm). Is anyone available to stay the entire time? or maybe switch off on shifts? 
(the Friday concerts go on until end of October so I won't be able to be the hostess during those Artwalks. But after that I'll be able to!!!)

**Comment by mmmaxine** [comment]
I upgraded your FB permissions, @MelissaIuliano
<https://github.com/melissaiuliano>! You should be able to create a FB
event now. :)

**Comment by MelissaIuliano** [comment]
Thanks!!!!

**Comment by hutchowen** [comment]
Thanks you guysssss!

**Comment by MelissaIuliano** [comment]
Thank you everyone for a good Artwalk!
big, big, BIG THANK YOU to @zee-em and @mmmaxine for setting up and hosting!!! Thank you, thank you, thank you!!!!!!!!
